### ISSUE TITLE
Orbital basis in calculations with SOC

### ISSUE THREAD

**Issue by MIraola** [zerothi/sisl#109]
**Describe the issue**

I have performed a SIESTA calculation with spin-orbit coupling (SOC) and loaded the Hamiltonian with the following lines:
```
fdf = get_sile(fname)
H = fdf.read_hamiltonian()
```
Then, I have checked the number of atoms and orbitals of each of them in H.geometry and compared with the dimensions of the Hamiltonian matrix, noticing that the order of the matrix is the double, because of the use of SOC; so that we can say that the basis of orbitals have been doubled. My question is, are the indices of orbitals corresponding to a particular atom one after the other in the basis in which the Hamiltonian is written?

Let me explain this question with an example and a couple of figures: imagine that I have a unit cell of 2 atoms, the first one with 2 orbitals |a> and |b>, while the second has another 2 orbitals |c> and |d>. When I perform a siesta calculation without SOC, the order of the indices of orbitals in the basis is the one shown in the attached fig1 (where an eigenstate of H expanded in the basis of orbitals is shown). Now, imagine that I repeat the calculation with SOC; is the order of the orbitals in the basis the one shown in fig2 or the one shown in fig3 ?

Note: figures are displayed in ascending order, i.e. fig1 is the one at the bottom, fig 2 is in the middle and fig3 at the top.

I hope I explained the question in a way easy to catch. Thank you for your help!

![fig3](https://user-images.githubusercontent.com/40389180/53046825-412ed000-3491-11e9-9d10-36dcc00b896b.jpeg)
![fig2](https://user-images.githubusercontent.com/40389180/53046826-412ed000-3491-11e9-9c38-8717a4f07580.jpeg)
![fig1](https://user-images.githubusercontent.com/40389180/53046827-412ed000-3491-11e9-81b1-71cab887e8e6.jpeg)

**Version details**
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
0.9.5
305080f5119b26cedaf5513ec6f9ea1389334ab9

**Comment by zerothi** [comment]
The orbitals in a sparse matrix (in `sisl`) is always ordered according to:

1) The atoms, i.e. `geometry.atoms[0]` is the first atom, `geometry.atoms[1]` is the second atom etc.
2) For each atom there exists a number of orbitals `len(geometry.atoms[0]) == geometry.atoms[0].no`. The Hamiltonian then comprises the orbitals in order of appearance in the atom object.
3) If doing a non-collinear or spin-orbit calculation every orbital has a consecutive "spin-up" and "spin-down" component for the spinors, otherwise there is no double number of orbitals.

For your figures:
`fig1`: Yes, this is how a polarized/non-polarized calculation would look like.
`fig2`: This is the correct order of orbitals, each orbital has both spinors consecutively.

**Comment by MIraola** [comment]
Perfect! Thank you for your answer.

**Comment by novidad21** [comment]
Can I have an update for this question? Let's suppose I have a spin-orbit included calculation and I would like to know the weight of the d_xy orbitals in a particular band. How should I implement it? Consider the following:
- First I go through every atoms and every orbital in `ham.geometry.iter_orbitals()`
- At every step I check whether the `orb.l `and `orb.m` satisfy that `m=-2` and `l=2`. If so, a store the running index into a list, let's say `idx_d`.

Now I have all the indices for the d_xy orbitals for spin up, let's say `[0,4,7]` and I have 14*2 (due to spin) orbitals alltogether.

How can I get the spin_down parts for the list? Is it `[14,18,21]`?

**Comment by zerothi** [comment]
Please see this tutorial for details: https://zerothi.github.io/sisl/tutorials/tutorial_siesta_2.html

Note that there are no indices for up/down in a SOC calculation, when you calculate the PDOS you get an additional index `[total, x, y, z]` so there you can just look up the details. So, find the `d_xy` orbital index, and then calculate PDOS for that your band, extract the orbital PDOS, and then you have it.

**Comment by novidad21** [comment]
Thank you for your answer.
