### ISSUE TITLE
Parallelization of "construct"

### ISSUE THREAD

**Issue by tanocalogero** [zerothi/sisl#21]
For very large systems this would be really useful.

**Comment by zerothi** [comment]
Since 613b8f724 the `construct` command has been overhauled and is MUCH faster (more than twice as fast).

For now I will close this issue as the OP has reported that for 395,000 atoms `construct` runs in 7 minutes.

Secondly, because `construct` now accepts a function for specifying the tight-binding parameters we are now not limiting `construct` to single orbital systems, nor with any flexible way of describing the parameters.

Thanks for the report!
If this becomes an issue later, please re-open this item.
