### ISSUE TITLE
Math on sisl CSRs is very slow compared to scipy csr

### ISSUE THREAD

**Issue by jonaslb** [zerothi/sisl#236]
For a delta-hamiltonian of 70200 atoms and 267300 orbitals, I am trying to put a complex constant times the overlap matrix on it. Using just the diagonal works fine enough, but of course using the overlap matrix means putting a lot more elements. Still, the overlap matrix contains "only" 22_200_750 elements (after using eliminate_zeros with atol=1e-5, that's down to 15_381_900).

```python
dH = CAP(...)  # (is a diagonal matrix on some orbitals)
S = si.get_sile("Hsys.nc").read_overlap()
S.eliminate_zeros(atol=1e-5)  # takes around 50 seconds
dH.H -= 0.01j * S  # Doesn't finish in a 20 minute window
```

```python
S = si.get_sile("Hsys.nc").read_overlap()
S.eliminate_zeros(atol=1e-5) 
S = S.tocsr()
dHcsr = dH.tocsr()
dHcsr -= 0.01j * S  # Finishes in less than a second
dH = dH.__class__.fromsp(dH.geometry, dHcsr)  # also doesn't finish in a 20 minute window
```

The problem seems to be the `_extend` function of the sisl CSR. It is used extensively on a row-loop-basis and requires (I think?) a copy of all the data every time.

I feel it is "slow enough" to warrant a bug report -- probably we could take some inspiration from Scipy on this matter, as it is so much faster.

**Comment by zerothi** [comment]
I am well aware of the problems with this. Sadly scipy's implementation is not compatible with what we have here.

Problem is that scipy is fast due to its C-implementation, but it does not allow multiple values per matrix index.

I have debugged this extensively in the beginning, and it was *not really* (:tada:) meant for that big matrices ;)
I should probably have another go at this.

However, some rules:
1. math is fast if the sparse patterns are the same.

So `eliminate_zeros` is almost always a really bad idea!

2. I have thought about offloading math to scipy sparse matrices, however, it depends on the size of the matrix (smaller matrices it doesn't have the value)

3. The `_extend` function will only copy if the matrix does not have space. The problem why this case is particularly bad is because every row gets more values, and this causes it to be re-allocated for every index. And this is very slow in python.

4. In your case I think it should be much faster to do something like this:
```python
dH = CAP(...)  # (is a diagonal matrix on some orbitals)
S = si.get_sile("Hsys.nc").read_overlap()
S.eliminate_zeros(atol=1e-5)  # takes around 50 seconds
SH = -0.01j * S
SH += dH
```
Could you try this?
If you could create a test case for internal use this would be nice? ;)

**Comment by jonaslb** [comment]
Ah, yes, it's a good idea to use the bigger matrix for the inplace op to avoid mutating the sparse pattern. Unfortunately, it is not the magic bullet here, it still doesn't complete in reasonable time. It seems the in-place operation is still going via `_ufunc_sp_sp` which constructs a new csr and uses `_extend` on every row.

**Comment by zerothi** [comment]
Agreed, it is still very slow... :(
The call to `_extend` is currently required since it returns indices for elements, and if not existing adds new element.

I'll have to debug this further but I think this will more or less require a re-write of the `SparseCSR` matrix format.

I also had an initial look at the sparse package for python which allows multi-dimensional sparse matrices. However, the problem is that what we really want is contiguous memory to pass the matrix to the Cython `Hk` functions.
If we don't have contiguous memory we will just move the problem elsewhere. And my hunch feeling is that `Hk` functions are much more used and thus more important to retain optimized.

**Comment by jonaslb** [comment]
Your suggested solution *should* not need to mutate the sparsity pattern, but it still causes trouble because it doesn't really do the operation in-place, but still creates a new output. Maybe the first thing could be to enable simpler `__iadd__` (and sub) for matrices that don't need to mutate their sparsity?

Then afterwards, I think it must be possible to calculate ahead of time the full sparsity pattern and only do reallocation once instead of `nrows` times. Ie. a new `sparsity_pattern_union(*operands)` to create a new empty sparse matrix, followed by doing fast non-sparsity-mutating in-place operations on it.

**Comment by zerothi** [comment]
> Your suggested solution _should_ not need to mutate the sparsity pattern, but it still causes trouble because it doesn't really do the operation in-place, but still creates a new output. Maybe the first thing could be to enable simpler `__iadd__` (and sub) for matrices that don't need to mutate their sparsity?

This would be viable, this is just a *bit* problematic since the entire machinery is offloaded using `numpy` ufuncs. Which enables all `np.exp(H)` stuff easily. So it needs to be done in the current scheme detecting whether `out` is equivalent to `self` (I think), and then take a different route.
The ufunc handling is very new, so I haven't looked too much into it.

> Then afterwards, I think it must be possible to calculate ahead of time the full sparsity pattern and only do reallocation once instead of `nrows` times. Ie. a new `sparsity_pattern_union(*operands)` to create a new empty sparse matrix, followed by doing fast non-sparsity-mutating in-place operations on it.

Yeah, I tried this the simple way by doing something like this:
```python
full_sp = reduce(lambda x, y: x + y.tocsr(), sps, 0.)
```
however, this also leads to problems since scipy may remove 0 when adding them.

Also, I am not sure this is the real cause. You would still need `_extend` (or ideally `_get`) to retrieve the indices of the indices. I think this is what is hurting performance, that you have to loop all rows to do it.
The only way out would be to do *more* indices at a time to reduce loop constructs and function calls.

**Comment by jonaslb** [comment]
Okay maybe I'll give it a look later. I'm pretty sure it will be an optimization to do a single allocation for data and indices (like scipy) first, and then move over/perform operations afterwards. Regardless of whether it's all C-optimized or not.

**Comment by zerothi** [comment]
> Okay maybe I'll give it a look later. I'm pretty sure it will be an optimization to do a single allocation for data and indices (like scipy) first, and then move over/perform operations afterwards. Regardless of whether it's all C-optimized or not.

You could try out the latest commit, that will pre-allocate too much space. Comparing with the previous commit you should see a difference related to the re-allocation, see [here](https://github.com/zerothi/sisl/commit/78b9e405cda2734386428807ffefdb30e9869cb1#diff-7af1b14ffe38012a67f1433853258c21R1326)

**Comment by jonaslb** [comment]
Okay I had to do an explicit call to SparseCSR.fromsp instead of SparseGeometry.fromsp to make use of these changes. But somehow, for some reason, it still ends up thinking that it needs to do an actual extension of the sparsity in `_extend` (I put in a ValueError to be completely sure it wasn't happening)... I will take a further look at it later

**Comment by zerothi** [comment]
Could you try the latest commit? I have ensured that `sisl/sparse.py.fromsp` is used everywhere! :)

**Comment by zerothi** [comment]
Ok, I added a small test, I checked for a matrix with 100000 rows with my latest fix, it is roughly 5 times faster (for that matrix size) so the bigger the higher speedup you'll see.

**Comment by zerothi** [comment]
Did you check again? I think the problem is partially solved?

**Comment by jonaslb** [comment]
Hey, got away from it and but just tried again. Now it takes 13 seconds, much more managable :)

**Comment by zerothi** [comment]
Great, I'll close then :)

**Comment by jonaslb** [comment]
So for now, if one wants to do `A+B` for larger systems, one should really do something like `A.__class__.fromsp(A.geometry, [A.tocsr(d)+B.tocsr(d))`
