### ISSUE TITLE
Inquiry about sisl to post-calculate the projected-bands

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#264]
**Describe the issue**
Good evening,
I read http://zerothi.github.io/sisl/docs/latest/tutorials/tutorial_siesta_2.html to try and understand how to calculate projected-bands in siesta. 
It seems that I will have to run SIESTA through python in order to get to the project band structure calculations.
Which is, unlike sgrid, where a simple command can extract information from grid.nc files, it does not seem to be the case with the link mentioned above. I was wondering if there is any way this could be further explained? 
Not sure if my question is clear or not. But if I have a siesta calculation in a folder in which i calculated PDOS and band structure what command in sisl should I use to extract the projected band structure if possible?
Otherwise with the link above, can python handle very large systems? Thank you and looking forward to your reply.
EL-abed
**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```python
import sys
print(sys.version)
import sisl
print(sisl.__version__)
print(sisl.__git_revision__)
```

**Comment by zerothi** [comment]
A fat-band calculation (or projected bands) calculation.

So a few things:

1. The link you provide don't run Siesta through Python. It uses the output from Siesta and post-processes it.
2. If the system is relatively small, say up to 2000-3000 orbitals it should be fine to do the calculation in sisl/Python. In practice sisl/Python should be able to handle even larger systems, but it may just take a long time :)
3. If your system is larger it may take a considerable amount of time and you should use the Siesta utilities, see in directories `COOP` and `Bands`
4. You can't use PDOS and the band-structure since the PDOS is averaged over the entire BZ and isn't k-point resolved.

**Comment by el-abed** [comment]
1- I am not sure even from the link how can I call out sisl like sgrid. If I am in the directory where I want to post process it, what command exactly should I use?
2- I used the utility bands to extact band structure. But, can it extract projected band structure?
3- What are the differences between COOP and Bands?

**Comment by zerothi** [comment]
1. There isn't a command for this, you have to create a Python script to do it. You can simply take the linked notebook and adapt to your needs.
2. Like I said, you have to use the utilities in COOP and Bands. Please read the readme files or follow item 4 [here](https://personales.unican.es/junqueraj/JavierJunquera_files/Metodos/Full-STO/Full-STO.html)
3. They are both needed for fat-bands.

**Comment by el-abed** [comment]
Thank you very much! It seems I will have to use COOP and Bands because my systems are very large.
Thank you again!
