### ISSUE TITLE
tutorials on DFT+U calculations in siesta +transiesta.

### ISSUE THREAD

**Issue by el-abed** [zerothi/sisl#271]
**Describe what you want to accomblish with TS+TBT+sisl**
plot transport (i-v curve + eigen channel ) + electronic (pdos + band structure) properties for heterogeneous 2D (or 3D) material structures.
Just would like to know if we can register in advance or not

**Comment by zerothi** [comment]
Thanks for the suggestion.  
We don't plan on LDA+U calculations since, as far as I know, none of us are experts in the LDA+U code.

However, from what I have heard around, one may use the +U part of Siesta together with TranSiesta provided one does careful convergence analysis.

As for the registration, that should be done via the [CECAM page](https://www.cecam.org/workshop-details/4).

**Comment by el-abed** [comment]
Thank you very much for the reply.
Just to confirm that the workshop is now going to be online. Is that correct?

**Comment by zerothi** [comment]
Yes.
