### ISSUE TITLE
sisl.viz._plotables

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#301]
@pfebrer

Your `_plotables` looks very similar to the Dispatch methods.

Could you clarify the needs of this contrary to the regular dispatch methods? And could we perhaps combine them to be based on the same base-classes?

**Comment by pfebrer** [comment]
Yes, you are right. I think it definitely can be implemented with dispatchers.

Some comments:
- `PlotEngine` is probably not needed anymore with the vision of implementing multiple backends in the same plot class (the backend will end up being a regular setting probably).
- It is very important that a default can be specified, because it looks dumb to `sisl.get_sile("file.bands").plot.bands()` (or same with a geometry).
- The `__dir__` method is important to me because it's used for autocompletion in IDEs, and it's a nice way of not needing to check the documentation to know what are your possibilities. I think in general dispatchers could really benefit from it, so maybe it can be incorporated in the base class?

**Comment by pfebrer** [comment]
Do you want me to do it or are you doing it already? hahah

**Comment by pfebrer** [comment]
This is solved with #317
