### ISSUE TITLE
Is there a tool to calculate Voronoi charges in sisl?

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#306]
I wanted to know if there's already such a tool. I can't seem to find it in the docs, but maybe I'm missing it.

If not, would you be interested in adding it? I need to use voronoi charges right now for different systems and I don't want to run SIESTA calculations again for each of them, so I could do it and compare to SIESTA to ensure that the results are right if you want.

**Comment by zerothi** [comment]
No, currently there isn't. You may find `scipy.spatial.Voronoi` useful. However, it is quite easy to implement the Voronoi charges in a simple fortran program, see e.g. the fortran sources.

Otherwise I would suggest you use `bader` tools to calculate the voronoi charges. That should also work.

The only thing to remember is the supercell connections.

**Comment by pfebrer** [comment]
Ok, thanks!

Would it make sense to use `DensityMatrix.density` to calculate the atomic electronic density? If not, what would be the best way to do it in sisl?

**Comment by zerothi** [comment]
You could do that. But if you already have stored the charge density grids from siesta, that is far better. `DensityMatrix.density` is quite slow, just as `wavefunction`.

**Comment by zerothi** [comment]
I am going to close this ;) 
Thanks for the question.

There are other places that need more focus than implementing voronoi. :)
