### ISSUE TITLE
How to output Green function of expanded molecule by transiesta+TBtrans+sisl?

### ISSUE THREAD

**Issue by tomato151** [zerothi/sisl#344]
**Siesta-Max-1.2.0 & sisl v0.10.0**
We try to use the following codes to output  the spectral function of the expanded molecule, but we are not sure whether this matrix is the spectral function (i.e.  the image part of the Green function) or not?
`import sisl`
`nc = sisl.get_sile('Cwire.TBT.nc')`
`d = nc.Adensity_matrix(0,0)`
If not, how can we get it?
Thanks!

**Comment by zerothi** [comment]
This is the spectral density matrix, please note the difference between the spectral matrix (`G Gamma G^\dagger`) and the density matrix `Re[G Gamma G^\dagger * e^(i k r)]`.

the `*density_matrix` is the latter, hence it is only a real matrix. Since it is expanded in the full supercell the returned matrix has a `[no, no * n_s]` shape such that one can find the overlap density matrix elements coupling between supercells.

If you want the Green's function density matrix, use `nc.density_matrix`.

**Comment by tomato151** [comment]
I've got it now! Thank you!
