### ISSUE TITLE
Installation in environments with no fortran installed.

### ISSUE THREAD

**Issue by bosonie** [zerothi/sisl#348]
A user of aiida-siesta reported failing of installing sisl in his environment because no fortran compiler is installed.
https://github.com/aiidateam/aiida-common-workflows/pull/207#issuecomment-859595256

Is this expected?
I believe it is not desirable.
This would be resolved by #281

**Comment by zerothi** [comment]
Yes, sisl requires a fortran compiler as noted in the installation instructions. So fully expected.

I'll close this since #281 tracks wheels for sisl.

**Comment by giovannipizzi** [comment]
I'd like to reopen this issue - other python packages might require a C or fortran compiler, but (when installing via pip) you could already provide wheels with binaries precompiled for common architectures. So, at least if you are running on those architectures, you can just `pip install`, and this is both very quick and does not require additional dependencies (like fortran). This is for instance important fort the issue above linked by @sphuber (we have a repository where a second-level indirect dependency is `sisl`, and we just need to get it installed in order to compile the docs). Would you be willing to look into this?

**Comment by zerothi** [comment]
Yes, I am aware and have had conversations with @pfebrer about a possible solution. So it is up in the works...

**Comment by bosonie** [comment]
Hi! The CI problem is definitely solved! Thanks!
However this issue I do not think it is. Do you now provide wheels?

**Comment by zerothi** [comment]
The wheels problem is tracked in referenced issue

**Comment by pfebrer** [comment]
We are working on this in this PR: https://github.com/zerothi/sisl/pull/427. We are very close to having wheels even for windows :)
