### ISSUE TITLE
sisl.viz tests open up *tons* of matplotlib figures

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#396]
**Describe the issue**

```shell
viz/plots/tests/test_grid.py::TestGridPlot::test_representation[matplotlib-complex_grid-1-imag]
  /opt/gnu/11.2.0/python/packages/3.9.7/sisl-dev/0/lib/python3.9/site-packages/sisl/viz/backends/matplotlib/backend.py:29: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
    self.figure, self.axes = plt.subplots()

```

perhaps it would be a good idea to close them using some kind of fixture. If more tests are added I fear it will consume too much. In any case it is a good idea to clean. :)

**Comment by zerothi** [comment]
@pfebrer

**Comment by pfebrer** [comment]
Yeah I already saw this warning. Actually I would like to not use `pyplot` so that things can get garbage collected as they normally do on python...

But I've been looking around the internet and it looks like then you have to handle the backend yourself:
https://stackoverflow.com/questions/16334588/create-a-figure-that-is-reference-counted/16337909#16337909
https://stackoverflow.com/questions/28631741/prevent-matplotlib-statefulness/28633419#28633419

I'm starting to get a bit mad at matplotlib :confounded: 

This problem will not occur only in tests but also in the normal usage of `sisl.viz`, so a fixture in the tests only would hide the problem.

Maybe the best solution is to add a `__del__` method to `MatplotlibBackend`, so that when the backend gets garbage collected, the figure is closed.

Something like:
```python
def __del__(self):
  plt.close(self.figure)
```

And then ignore matplotlib's warning because we know that when the garbage collector acts, it closes all figures for plots (more specifically `MatplotlibBackend` instances) whose reference count is 0.

What do you think?

**Comment by zerothi** [comment]
I think it is easier to use an `autouse` fixture in `pytest`, see here: https://docs.pytest.org/en/6.2.x/fixture.html

So some fixture in the viz directories. :)
This actually is not that much work and it is what matplotlib does.

**Comment by pfebrer** [comment]
But my point is that this will only remove the problem from tests. The problem would still exist with normal usage of the package, we would just hide it in the tests.

If the plots are generated by running a script, this will probably not be a problem. But if the user generates plots in a notebook, matplotlib figures will stack and we won't have any way of telling which figures need to be deleted, because the sisl plot object that keeps the reference to the figure will be inaccessible (or already deleted by the garbage collector).

**Comment by zerothi** [comment]
Yes. And I think this is fine. I know of no other codes that monkey patches matplotlib to kill figures. So I think this shall only be fixed for tests.

**Comment by pfebrer** [comment]
I was proposing to add it in our `MatplotlibBackend` class, not to monkey patch `matplotlib`. The `__init__` method initializes the figure:

https://github.com/zerothi/sisl/blob/5cd22e72af808d8b8a90b136755b05d19c0c78cb/sisl/viz/backends/matplotlib/backend.py#L26-L30

So to me it made perfect sense that when the object was removed the figure was closed (hence the proposal to add the `__del__` method to this class).

But it's fine, I'll just avoid the warning in tests then.

**Comment by pfebrer** [comment]
I'll keep this in my head for if it becomes a problem. It is not that straightforward because the user might grab the figure and want to keep it even after the sisl plot object is deleted, god knows why. In that case, the figure shouldn't be closed.

**Comment by zerothi** [comment]
> I'll keep this in my head for if it becomes a problem. It is not that straightforward because the user might grab the figure and want to keep it even after the sisl plot object is deleted, god knows why. In that case, the figure shouldn't be closed.

Agreed, good point. Lets not do anything about that then!
