### ISSUE TITLE
`_a` not defined

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#437]
This line: 

https://github.com/zerothi/sisl/blob/b49db223fba79c1cc62a948bc878ddecab45dacc/sisl/io/siesta/siesta_nc.py#L160

raises an error because `_a` is not defined. I guess it's time to run the static analyzer again :)

**Comment by pfebrer** [comment]
All the errors I see for `sisl.viz` are not errors actually. It seems like pylint can't understand `*args, **kwargs` because most errors just say that a given argument is not passed, when indeed is passed through either args or kwargs.

**Comment by zerothi** [comment]
I agree, the problem is that sometimes this error might be important, if there was a way to turn off this for methods with `*args, **kwargs` it would be nice, but I can't see how. Basically we should update `pyproject.toml` to some sensible disabled patterns. But it seems finetuning of what is disable is also annoying.

In fact many things are just horribly annoying in pylint, take this:
```python
if a == 0:
    return 1
elif a == 1:
   return 2
return 3
```
this will pylint mark as wrong usage, a bug-report was made, but the devs said it is intended, they suggested changing these things to:
```python
if a == 0:
    return 1
if a == 1:
    return 2
return 3
```
I think these things are just annoying and not really helpful...

**Comment by pfebrer** [comment]
Hmm yeah, well these things are open to discussion, since both will run just exactly the same and it's a matter of taste/stuborness.

Instead of disabling, I would just enable the errors that you think are important, i.e. basically undefined variables.
