### ISSUE TITLE
Mixing history reset with clear() not working

### ISSUE THREAD

**Issue by tfrederiksen** [zerothi/sisl#460]
After installing the current development version of sisl
```python
>>> print(sys.version)
3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
>>> import sisl
>>> print(sisl.__version__)
0.12.2.dev83+g8b019f96
```
it appears to me that the resetting of mixer history with `clear()` has "disappeared":
```python
>>> import sisl
>>> mix = sisl.mixing.PulayMixer(0.7, history=7)
>>> mix.clear()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PulayMixer' object has no attribute 'clear'
```

**Comment by zerothi** [comment]
I am sorry I changed this... :(

I thought it wasn't used.

The problem with the mixing routines was that they were not really well implemented. The DIIS mixers inherited a bunch of unrelated things.

I have now changed it so that the history is an attribute in the DIIS mixer. This enables one to re-use the same history for different mixers, and some others things (I am exploring some stuff with Siesta mixers).

The mixers have been needed a work-around for some time...

The current way is to do this:
```python
# portable with older versions
try:
    # new way
    mix.history.clear()
except:
   # old way
   mix.clear()
```
which should do it.

Problem is that I don't think the pulay mixer should have any idea about the history, per see. The history could be used for many other things and hence an external history could be used.

Sorry, should have checked with hubbard...

**Comment by zerothi** [comment]
I hope the changes I did, did not break other things. ;) Let me know!

**Comment by tfrederiksen** [comment]
No problem, I didn't realize the new way is simply `mix.history.clear()`. I'm happy with this and I think we can easily implement this change in Hubbard.

**Comment by zerothi** [comment]
Great. Now it will also enable one to pass other variables for creating mixing coefficients.

Say if you want to mix the density, based on the magnetization and not the density it-self, then you could do something like this:
```python
        # Measure of density change
        ddm = ni - self.n
        ddM = ni[1] - ni[0] - (self.n[1] - self.n[0])
        dn = np.absolute(ddm).max()

        # Update occupations on sites with mixing algorithm
        if mixer is None:
            mixer = sisl.mixing.DIISMixer(weight=0.7, history=7)
        self.n = mixer(self.n.ravel(), ddm.ravel(), ddM.ravel()).reshape(self.n.shape)
```
note, this is not backwards compatible.

The idea is that the *first* two elements are what gets mixed, and the *last* element is the coefficient variable for the metric.

**Comment by zerothi** [comment]
Also, you don't need `ravel` anymore! :)

**Comment by zerothi** [comment]
Can I close this?

**Comment by tfrederiksen** [comment]
Yes, thanks! Note that, as far as I can see, `clear` is not covered by the tests.

**Comment by zerothi** [comment]
No, that is true. The tests are not complete on the mixing stuff... :(

**Comment by zerothi** [comment]
tests added!

**Comment by tfrederiksen** [comment]
> tests added!

Can you point me to these tests, can't find them.

**Comment by zerothi** [comment]
sorry, forgot to add the file, it should be there now!
