### ISSUE TITLE
Reading hamiltonian or density matrix hangs

### ISSUE THREAD

**Issue by oroszl** [zerothi/sisl#492]
**Describe the bug**

For certain calculations, reading the hamiltonian or density matrix hangs.

**Reproducable code**
```python
import sisl 
fdf = sisl.get_sile("Cr3.fdf") # this bit runs without a problem
geo = fdf.read_geometry()  # this bit runs without a problem
```
```python
rho = fdf.read_density_matrix() # this runs but hungs in running without failing
```

```python
ham = fdf.read_hamiltonian() # this runs but hungs in running without failing
```

You can find the details of the whole scf calculation [in this package](https://www.dropbox.com/s/4q5lx5mjnx5m72w/Cr_new.zip?dl=0).

**Version details**

```python
3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
0.0.0.dev+eacb8351ff416ad9f7f93732777c3d7931c5f711
```
I tested everything in a clean conda environment prepared according to the sisl install [manual](https://zerothi.github.io/sisl/installation.html#stable)

**Comment by zerothi** [comment]
Thanks for finding this bug.

This was a regression when rewriting the HSX code. I would recommend you to _not_ rely on HSX file format in 4.1 since it may not always work, sisl should be able to abort if there are problems. The `CDF.Save t` or `TSHS.Save` are safer choices since they also contain the Fermi level and exact geometry. So prefer these formats!

Thanks!

**Comment by oroszl** [comment]
In the run I also had `CDF.Save T` and the .nc file is also present. I thought the reader would read the `.nc` file first, and if that was not present than it would go further.

**Comment by zerothi** [comment]
From the files you uploaded something this is not clear:
```shell
redata: Save all siesta data in one NC              =   F
```
And indeed it prefers files which are *safer* to parse.

**Comment by zerothi** [comment]
The `DM.nc` and `DMHS.nc` files are currently not supported...

**Comment by oroszl** [comment]
I think that must have been a source of confusion for me..
I need somehow SIESTA to produce `SYSTEM_LABEL.nc` ?

these were the bits regarding output in my fdf:
```bash
WriteMullikenPop       1
WriteEigenvalues       T
WriteForces            T
WriteCoorStep          T

SaveHS                 T

Write.DM.NetCDF        T
Write.DMHS.NetCDF      T
CDF.Grid.Precision     double
CDF.Save               T
DM.UseSaveDM    T
```


Would the line 
```
SaveHS                 T 
```
make SIESTA think not to write the `SYSTEM_LABEL.nc ` output?
Can it happen that there is some problem with the way SIESTA was compiled?

**Comment by zerothi** [comment]
Hmm, for some MD simulations we do not allow writing the CDF files, because the format is not clarified. Basically when doing an MD you do _not_ want to write things all the time, and writing content to all these files all the time is a waste of CPU cycles. Rather, do your MD without all this IO, then take out the snapshots and do single shot calculations (no MD) for extracting information.

This is why the CDF is disabled in this calculation.
