### ISSUE TITLE
Kernel sometimes dies when reading the SIESTA output hamiltonian. 

### ISSUE THREAD

**Issue by martinirizar** [zerothi/sisl#512]
**Describe the issue**

For electronic structure calculations, I run SIESTA with the following lines in the input: 

CDF.Save true
CDF.Compress 9
SaveHS true
SaveRho true

Afterwards, if the calculations finish correctly, I use the following commands to make the post-processing in SISL:

```python
import sisl
import numpy as np

H = sisl.get_sile('input.fdf').read_hamiltonian()
```

It always worked correctly so far, but I am working with a molecule with relatively few atoms (56, carbons and hydrogens), SIESTA finishes the job but SISL fails to read the hamiltonian. In jupyter notebook, it says: "The kernel appears to have died. It will restart automatically." In python 3.9: "STOP Error in reading data, not allocated".

**Comment by tfrederiksen** [comment]
Did you try executing the above lines as a stand-alone script (instead of in a jupyter-notebook)?

**Comment by martinirizar** [comment]
Yes, I tried on a .py script, executing with python 3.9. It stops and throws the following error:  "STOP Error in reading data, not allocated".

**Comment by zerothi** [comment]
I believe this is because of #492, are you sure that the `nc` file is present in the directory? If not, then ensure that siesta has been compiled with sufficient libraries and flags to enable the `nc` file output.

In case it is not trying to read from the `HSX` file and you don't want/have support for the `nc` file, then I would recommend you to add these flags to your fdf input:
```shell
TS.HS.Save true
```

**Comment by zerothi** [comment]
Or alternatively try out the latest commit on `main`

**Comment by martinirizar** [comment]
I have re-run the calculations not only with ``TS.HS.Save true ``, but also with a smaller ``CDF.Compress`` value. Again, I get the ``nc`` files, but SISL keeps dying. 

In principle, I have checked the `nc` files with command `ncdump`, and they do not look like deficient, they are simmilar with some other systems' outputs that have previously worked well with SISL. 

I attach the output (and some input) files to this message, in case it is of interest. Thanks beforehand. 

[files.zip](https://github.com/zerothi/sisl/files/10010720/files.zip)

**Comment by zerothi** [comment]
Thanks for the update, I'll have a look ASAP. Could you tell me which sisl version you are using?

**Comment by martinirizar** [comment]
Of course. I am using the 0.12.1 version.

**Comment by zerothi** [comment]
> Of course. I am using the 0.12.1 version.

Could you first try and update to the latest development version? I am not on at my computer for the moment, I suspect it might already have been fixed.

**Comment by tfrederiksen** [comment]
> I attach the output (and some input) files to this message, in case it is of interest. Thanks beforehand.

I notice from your zip file you have `biph_pass.HSX` file but not  `biph_pass.nc`. Could you try to produce and read the latter?

**Comment by tfrederiksen** [comment]
I can reproduce the error message trying to read from files.zip above using the development version of sisl (730155dd).

**Comment by zerothi** [comment]
> I can reproduce the error message trying to read from files.zip above using the development version of sisl ([730155d](https://github.com/zerothi/sisl/commit/730155dd3fd13970937fa7f116a5f6eb6a880e22)).

Thanks for trying, when I get back to the computer I'll have a look!

**Comment by martinirizar** [comment]
In the SIESTA calculations made so far, there was never the `system.nc` file, since I was making the postprocessings from relaxation calculations (SIESTA does not create `system.nc` when MD/relaxation calculations). However, I have never had problems in SISL using only `system.HSX` and the `element.ion.nc` files before. 

I am recomputing the calculations without relaxing the structure. I will keep you updated ASAP.

**Comment by tfrederiksen** [comment]
I reran your siesta calculation (without relaxation though) to produce a new `system.HSX` file. With that one I get no error reading with sisl. This points to a siesta issue, no?

**Comment by martinirizar** [comment]
It might be one of the options to be a siesta issue, but the `system.HSX` files where apparently correct even for structural relaxation calculations for the very rest of the systems. Anyhow, thanks a lot for your help. Still trying new thing to see if this problem can be avoided. I'll keep you aware.

**Comment by zerothi** [comment]
My general recommendation is to not use hsx files prior to siesta version 5 (note that 5 is not yet released). In these old versions one should prefer the tshs file.

The reason is that the hsx file did (in versions prior to 5) not contain the geometry, and so ambiguities could arise.

I will still have a look at the root cause, but as @tfrederiksen says it could be siesta in this case...

**Comment by martinirizar** [comment]
Thanks a lot!

**Comment by zerothi** [comment]
Ok, this is really weird.

The problem stems from https://github.com/zerothi/sisl/blob/730155dd3fd13970937fa7f116a5f6eb6a880e22/sisl/io/siesta/_src/hsx_read.f90#L372

However, that line is coded correct.
The problem seems to be a compiler bug that I can also reproduce with GCC 11.2.0.

For instance, when adding this line:
```fortran
  print *, Gamma, no_u == no_s, Gamma .neqv. (no_u == no_s)
```
I get the output
```shell
T T T
```
which should never occur (neqv means logical non-equivalence).
I have tried to create a small minimal reproducing code, but I can't..
```fortran
program t

  integer :: n, m
  logical :: Gam

  call wrt()

  open(238, form="unformatted", status="old")
  call rd(Gam, n, m)
  print *, Gam, n == m, Gam .neqv. n == m
  call rd(Gam, n, m)
  print *, Gam, n == m, Gam .neqv. n == m
  call rd(Gam, n, m)
  print *, Gam, n == m, Gam .neqv. n == m
  call rd(Gam, n, m)
  print *, Gam, n == m, Gam .neqv. n == m

  close(238)
  
contains

  subroutine wrt()

    open(238, form="unformatted")
    write(238) .true.
    write(238) 14, 352
    write(238) .true.
    write(238) 14, 14
    write(238) .false.
    write(238) 14, 352
    write(238) .false.
    write(238) 14, 14
    close(238)
    
  end subroutine wrt

  subroutine rd(Gam, n, m)
    logical, intent(out) :: Gam
    integer, intent(out) :: n, m

    read(238) Gam
    read(238) n, m

  end subroutine rd
    
end program t
```
I think I'll have to report this upstream... But this is just weird...

I have now tried to circumvent this by spelling out the checks, I could easily read your output file.

In any case, I would still recommend a different format than the HSX files. :)

Thanks for reporting this!
