### ISSUE TITLE
Change neighborfinder returns to a tuple of indices and supercell indices

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#744]
**Describe the feature**
I think this would be more natural.

instead of `[io, jo, a, b, c]`, it should return `[io, jo], [a, b, c]`

**Comment by zerothi** [comment]
But then, probably `jo` should just be in a supercell index?

**Comment by pfebrer** [comment]
The way I see it the finder should just find. If someone later wants to convert the indices according to a given auxiliary cell and a given ordering convention they can do it. But in my opinion it should not be the responsability of the finder.

Supercell indices are mostly worthless without an auxiliary cell size and an ordering convention, so I don't like returning them as the "raw" return. E.g. if someone wants to just use the finder (not the rest of sisl), they will likely prefer supercell shifts.

In my opinion it would be better to keep the raw return and maybe implement wrappers that convert to supercell indices. E.g. if he finder machinery is used in `Geometry.close`.

**Comment by zerothi** [comment]
Agreed, so it should return `jo + no * index_of_supercell`, no?

**Comment by pfebrer** [comment]
I don't know what you agreed to, but to me it doesn't look like we agree :sweat_smile:

**Comment by zerothi** [comment]
> I don't know what you agreed to, but to me it doesn't look like we agree 😅

`geom.close(ia)` by default returns `ja` which is a supercell index. That was my understanding that you agreed to?

**Comment by pfebrer** [comment]
Ah ok, yes on `Geometry.close` I think keeping the current behavior is the way to go!

**Comment by zerothi** [comment]
But I also think it should be here as well, why not?

From the supercell coupling it is very easy to convert to orbital couplings, and even getting the isc from a single number would be trivial.

So neighbor lists should return supercell indices.

**Comment by pfebrer** [comment]
And what should the finder do, return `nsc` as well? If the neighbors are requested only for a given atom, how can the finder know `nsc`?

If someone uses just the finder because is efficient (but not `sisl.Geometry`, `sisl.Hamiltonian`, etc ...), they will surely want the supercell shifts, not the atomic supercell indices with sisl's convention.

**Comment by zerothi** [comment]
well, the entirety of `sisl` is based on the `nsc` concept, and it may be used to gauge the range of couplings.

So I don't necessarily agree, while I can see both arguments.
Converting from supercell indices to isc is quite trivial:
```python
isc = geom.a2isc(jo)
```
done...
I think this is more of how should we encourage sisl to be used. The `finder` is used on a `Geometry` and this should hold the `nsc` information, so it is intrinsically known for the geometry.

Just as `close(ret_isc)`, we could have that in the `finder`, but I think generally we should work in supercell indices.

**Comment by pfebrer** [comment]
So `nsc` should be determined before using the finder? And the finder should not return neighbors outside that auxiliary cell?

I think both things can coexist. There can be a "raw" interface and a wrapped interface for `Geometry`. But I think that supercell indices can be obscure in some cases, so I like that the finder raw returns are as transparent as possible. Some things that I don't like of being forced to get the supercell indices:

1. The natural thing that you get when finding neighbors is the supercell shifts. So if that is what you want you would be converting atoms to supercell indices to then recalculate the shifts, which you had for free in the first place.
2.  If you hold an array with neighbors and the auxiliary cell changes, suddenly your neighbors are wrong. So the array of neighbors should have an `nsc` associated somehow to check compatibility in some cases where you can't be sure that the geometry's auxiliary cell has not changed. 
3. The auxiliary cell is not a property uniquely defined by the `Geometry`. In SIESTA it depends on the KB projectors, for example. It is hard to keep track sometimes. E.g. if you are using a geometry read by SIESTA and a sisl created one at the same time.
4. A user that is new to sisl will be confused by the returns of the finder. Maybe a not so new user too, since this is a concept that is not the first thing you learn.

Probably most uses of the finder will be through the already present interfaces. The only thing that people will notice is that it is faster. If somebody wants to use the finder directly, they can access the raw data directly. I would say it would be more like a low level interface. We could also allow the finder to return both things depending on what the user wants.

**Comment by pfebrer** [comment]
I like the idea that the finder returns this class!

But do you think that `Geometry.close` needs to be changed? This can be something that the finder returns and then internally in `Geometry.close` it is converted to keep the API the same as it is now.

**Comment by zerothi** [comment]
But isn't your argument that `close` returns also in supercell indices, which is a bit counter-intuitive?
I think it would be nice if we could streamline this, no?

**Comment by pfebrer** [comment]
Hmm but changing this in `close` would be chaos for everyone, no? :sweat_smile: 

Also I think there is fine, because it's something more tied to the `Geometry` class. I see the neighbour finder being used in situations where the user is just looking for the most efficient way to get all neighbors . E.g. to build graphs for ML.

**Comment by zerothi** [comment]
You are probably right. Then I think we should split the return values?
It is more clearer that `isc[:, 0]` refers to offsets along the first lattice vector.

**Comment by pfebrer** [comment]
Cool, I think it's the best approach seeing that there might be different users interested in different things. And also it makes sure that the user knows what they are using.

I guess it could also be an `xarray.Dataset` (with variables like `ia`, `ja`, `isc`, ...), but I don't know if the world is ready for that :sweat_smile:

**Comment by zerothi** [comment]
> Cool, I think it's the best approach seeing that there might be different users interested in different things. And also it makes sure that the user knows what they are using.
> 
> I guess it could also be an `xarray.Dataset` (with variables like `ia`, `ja`, `isc`, ...), but I don't know if the world is ready for that 😅

No, I think not ;)
Lets stick with a simple object :)

**Comment by pfebrer** [comment]
What do we do with the `find_neighbors` method? That one returns a list where each item contains the neighbors of a given atom.

Should each item in the list be a neighbor? Or should that distinction disappear and the custom object should have a method to iterate over atoms?
