### ISSUE TITLE
Format in sparse functions.

### ISSUE THREAD

**Issue by jmllorens** [zerothi/sisl#75]
**Describe the issue**

I started today a play with `sisl`. I have installed it with `conda` and I got a small issue:
To install `sisl 0.9.2-py36h18b3941_3` conda needs to DOWNGRADE `scipy` from `1.1.0` to `1.0.1`
In the end, I have installed `sisl-0.92` build `py36_2` which works with `scipy 1.1.0`.

Then I tried the tutorial on the graphene material that appears in the `README.md`. I got the following error:
```
  File "./lib/python3.6/site-packages/sisl/physics/sparse.py", line 1048, in eigh
    P = self.Pk(k=k, gauge=gauge, format='array')
  File "./lib/python3.6/site-packages/sisl/physics/sparse.py", line 581, in _Pk_unpolarized
    return self._Pk(k, dtype=dtype, gauge=gauge, format=format)
  File "./lib/python3.6/site-packages/sisl/selector.py", line 266, in __call__
    returns = routine(*args, **kwargs)
  File "./lib/python3.6/site-packages/sisl/physics/sparse.py", line 267, in _Pk_dot
    return V.asformat(format)
  File "./lib/python3.6/site-packages/scipy/sparse/base.py", line 326, in asformat
    return convert_method(copy=copy)
```
After looking at `base.py` and `sparse.py`, it seems that there is a problem in `sisl` with the format. I might be wrong, but it seems to me that if `V` is a sparse matrix one can only use the `asformat` method to convert it into another sparse format and `array`, as far as I know, is not listed in scipy as a sparse matrix class. Perhaps, using the method `toarray()` directly is more suitable This is done, for example, in `_Pk_spin_orbit_dense`, where depending on the `format` argument there is a different call. I think this problem is related with the DOWNGRADE in `scipy` I mentioned before, because `base.py`introduced the `copy` argument in a recent commit.

In any case, please let me congratulate you for the excellent code which has a great potential.

José M. Llorens.

**Version details**
Run the below code and add to issue (if an issue is relevant for the issue):
```
>>> print(sys.version)
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
>>> import sisl
>>> print(sisl.__version__)
0.9.2
```

**Comment by zerothi** [comment]
Thanks for the bug-report.

Indeed this is because of scipy 1.1.0, in fact I have made a PR to fix this backward incompatibility introduced in scipy.

See e.g. https://github.com/scipy/scipy/pull/9017 which fixes this issue.

To circumvent you could force the format to be `csr` and then call toarray subsequently. Or downgrade to 1.0.0.

However, I know that many of the routines *are* using this `format` method explicitly why I am rather worried about the scipy 1.1.0 implications elsewhere... The bug you find is the _only_ problem scipy 1.1.0 introduces for sisl. :(

Well, there is not much I can do for the 0.9.2 release. I am considering implementing fixes for this, however it may be cumbersome to track down all cases... Which is why I am rather reluctant... :(

Secondly, I would highly suggest you to download and install the development version of sisl, I really should release it soon so the new features become available! Its interaction with siesta has much increased.

Thanks for your kind words, and thanks for helping me improve the software.

**Comment by zerothi** [comment]
Let me also note that the sisl-0.92 build py36_2 was created before 1.1.0 existed, hence it did not know that they weren't compatible. So the fact that they are listed as compatible is false :(

**Comment by zerothi** [comment]
Turns out the new implementations in sisl has very few calls. So I fixed this in all future versions.

**Comment by jmllorens** [comment]
These are good news. It is not a big deal, but from my experience, the use of a software depending on an old version of a package ends up in messing the conda base environment. After reading your reply, which makes full sense, I started a virtual environment for sisl, which has the small problem of having to activate the environment before using the code. 

Thank you for your quick answer.

**Comment by zerothi** [comment]
I completely agree. I was also quite disturbed when I found out the regression in scipy... :(
