### ISSUE TITLE
I-V curve with tbtrans

### ISSUE THREAD

**Issue by masume70** [zerothi/sisl#820]
Hello,

I have a question about obtaining an I-V curve using TBtrans. Is it possible to get the I-V curve without performing transiesta calculations and using only TBtrans? As far as I know, we can read the I-V curve from the output of TBtrans. So, is it possible to obtain it using just sisl and TBtrans without transiesta?
Thanks,
Masoumeh

**Comment by zerothi** [comment]
Yes and no.

Generally an applied bias will change the electronic structure, due to charge renormalizations, and fields etc.

Hence, one cannot do I-V curves from models calculated at 0 V.

Yet, TBtrans *does allow* one to do I-V curves, even if the electronic structure is not self-consistently solved with the applied bias. 
If you do, I would recommend you to add something like
```
%block TBT.Elec.<name>
  V-fraction 1
%endblock
```
to your electrode blocks. This will simulate a potential shift in the device coupling region between the electrodes and the device.
This will not do anything if you have an orthogonal basis.

So, my recommendation is no.

**Comment by masume70** [comment]
Thank you very much.
I have one more question: The image below is derived from experimental results. Could you please guide me on how to simulate it using sisl and TBtrans? 
![Screenshot_2024-08-28_10-18-30](https://github.com/user-attachments/assets/fb6c5a40-8db3-453e-8758-91f92a259545)

**Comment by zerothi** [comment]
Sorry. That can be very difficult, and I simply don't have the time to answer all requests that comes by like this. It depends on a lot of things.... So ain't easy to answer generically.

**Comment by masume70** [comment]
Thanks
