### ISSUE TITLE
sisl.io.siesta.fdf._r_basis_fdf does not actually read the basis

### ISSUE THREAD

**Issue by juijan** [zerothi/sisl#90]
I am not sure whether this should be considered a bug or whether it is not implemented/unwanted feature, however ``sisl.io.siesta.fdf._r_basis_fdf`` does not read the ``PAO.Basis`` block. This can lead to problems, when creating ``Sile`` object from the ``fdf`` file and calling ``read_hamiltonian``. This will attempt to read the local ``HSX`` or ``TSHS`` file which can contain more obritals than geometry (with only one (default) orbital per atom) passed as a keyword argument to ``sisl.io.siesta.binaries.hsxSileSiesta.read_hamiltonian`` (or ``...tshsSileSiesta...``).

To reproduce this is issue place a ``fdf`` file and the corresponding ``HSX`` file in the same folder and run the script:
```python
import sisl as s
fdf = s.get_sile("test.fdf")
h = fdf.read_hamiltonian()
```
[fe_sp_polarized.zip](https://github.com/zerothi/sisl/files/2566381/fe_sp_polarized.zip)

**Comment by zerothi** [comment]
Agreed, this is a known issue. :(

**Comment by zerothi** [comment]
I haven't decided exactly what to do in those cases because the `PAO.Basis` block is rather difficult to parse consistently (it has many options).

So for now I ensured the user would be notified if this happened.

Reading stuff using the `fdf` file is definitely preferred but is _very_ complicated.

A fix could be that if the passed geometry fails it should try again without the geometry (and thus the geometry would be a *fake* geometry, but with correct orbitals.

Generally, the required files for the basis information should be there and thus generally it doesn't happen... :(
