### ISSUE TITLE
sc arguments should be named cell

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#95]
**Describe the bug**
`sc` keyword arguments are used in a few places.

All these should be named `cell` to make it clear what it is.

The main problem is that `sc` has been used since the beginning, so probably we need to have it allowed (until it truly becomes deprecated)

The following should be changed:

- [x] Change `SuperCell` to `Cell`
- [x] Change `sc` arguments to `cell`
- [x] Allow `sc` arguments via `**kwargs`` for fall-back and backward compatibility

Now I have a problem with the attached supercell instances. E.g. `Geometry.sc` (and all the other classes) is now a bit misleading.

How should this object be renamed (**HELP WANTED**):
- `obj.abc` for a-b-c lattice vectors
- `obj.uc` for unit-cell
- `obj.c` for cell
- `obj.cell`, this is the only thing that won't work because `obj.cell` already refers to the cell-vectors
- `obj.*` other suggestions?

**Comment by zerothi** [comment]
The branch #99 introduces the changes noted above.

I would like some comments regarding the last thing mentioned above @tanocalogero @tfrederiksen @sleith-dk @sofiasanz @brandimarte @jonaslb @juijan @jmllorens

Sorry for pinging if you are uninterested :)

Any suggestions? :-D

**Comment by jonaslb** [comment]
The cell vectors are in both `geom.cell` and `geom.sc.cell`, right? Perhaps an idea would be that this ambiguity should be resolved entirely rather than just giving them new names. 
For example, the cell could *always* be a (Super)Cell object OR the supercell's functionality could be put under each relevant class that uses it as a mixin class (so, inheritance). 

In either case that would be a bit of a bigger change than a rename, of course. If you stick with that, then it should at least have a name that makes it clear that is has "more" than just the cell vectors. And since "explicit is better than implicit", I'd try to refrain from using one, two- or three-letter abbreviations. But then you end up back at `supercell` (or `super_cell`) as a good name in my opinion.

**Comment by zerothi** [comment]
@jonaslb yes, that is true, however, the problem is that the object `Cell` (old `SuperCell`) has many methods allowing to extract information such as `sc.fit` etc. and many functionalities requires one to access these methods on the fly.
Agreed, it might be better to force users to explicitly use `<>.cell` and then de-reference the used methods.

I would however try to refrain from using `super_cell` because this forces the cell to be a "supercell". For cases where the *super* isn't required it may be counter intuitive to have *super* in the name. Hence I think perhaps `obj.cell` would be better. Although one would then see lots of `obj.cell.cell`? hmm...

**Comment by jonaslb** [comment]
Okay -- but if not `supercell` then I think that `cell` is the only other reasonable option (that I can think of). The existing `cell` should then be removed in favor of the `Cell` object. I can see that `obj.cell.cell` is weird, maybe `obj.cell.basis` or `obj.cell.vectors` (or `abc`, as you suggested yourself) is better then? Possibly putting an alias into `CellChild` (that I just realized existed!) via `@property` so that the matrix can be accessed directly via `cellchild.basis` or whichever.

**Comment by juijan** [comment]
I agree with jonas' ideas.
However, I am not sure whether the name ``supercell`` or ``sc`` is indeed counter intuitive. One could always argue that for those cases where the _super_ is not required the super cell and unit cell simply coincide.
Alternatively the name ``lattice`` might be justifiable as it is the structure underlying to the ``Geometry``, combining the unit cell and supercell ?!
However replacing the old ``cell`` by the new ``Cell`` object seems most intuitive.

**Comment by zerothi** [comment]
@juijan thanks for your take on this!

**Comment by zerothi** [comment]
I am beginning to be more keen on using `Lattice`, it is short! :+1:
